deploy: true
secret_id: rds-secrets
project_id: sw-dev-test-prj-itp-secrets

labels:
  environment: dev
  team: backend
  app: my-app

annotations:
  description: Service account key
  owner: backend-team

replication_type: auto
replication_locations: []
kms_key_name: null

rotation_period: "2592000s"
next_rotation_time: "2025-06-01T00:00:00Z"

ttl: null

versions:
  v1:
    secret_data: my-db-password-value
    enabled: true

iam_bindings: []